import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./component/Layout";
import N8nChat from "./component/N8nChat";
import { createTheme, ThemeProvider} from '@mui/material/styles';
import { purple } from '@mui/material/colors';
import { muiTheme } from "./style/theme";
import ClientProviders from "./component/ClientProviders";

const theme = createTheme({
  palette: {
    primary: {
      main: purple[500],
    },
    secondary: {
      main: '#f44336',
    },
  },
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ClientProviders>

        <Layout />
        {children}
         </ClientProviders>
        
         {/* <N8nChat /> */}
      </body>
    </html>
  );
}
